/********************* ROLES **********************/

/********************* UDFS ***********************/

/****************** GENERATORS ********************/

CREATE GENERATOR GEN_SAUVEGARDE_ID;
/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

/******************** TABLES **********************/

CREATE TABLE CHEMIN_SAUVEGARDE
(
  EMPLACEMENT_DE_SAUVEGARDE Varchar(1000)
);
CREATE TABLE FICHIER
(
  ID_SAUVEGARDE Integer,
  DATE_FICHIER Bigint,
  EMPLACEMENT_FICHIER Varchar(1000)
);
CREATE TABLE HORAIRE
(
  HEURE Integer,
  MINUTES Integer,
  ARRET_MACHINE Integer,
  ENVOI_MAIL_ST Integer
);
CREATE TABLE LISTE_EXCLUT
(
  EMPLACEMENT_FICHIER Varchar(1000)
);
CREATE TABLE LISTE_FICHIER
(
  EMPLACEMENT_FICHIER Varchar(1000)
);
CREATE TABLE PLANIF
(
  JOUR Varchar(255),
  IS_SELECTED Integer
);
CREATE TABLE SAUVEGARDE
(
  ID_SAUVEGARDE Integer,
  DATE_SAUVEGARDE Bigint,
  EMPLACEMENT_SAUVEGARDE Varchar(1000)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER ID_SAUVEGARDE FOR SAUVEGARDE ACTIVE
BEFORE INSERT OR UPDATE OR DELETE POSITION 0
AS 
BEGIN 
	/* enter trigger code here */ 
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER SAUVEGARDE_BI FOR SAUVEGARDE ACTIVE
BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID_SAUVEGARDE IS NULL) THEN
    NEW.ID_SAUVEGARDE = GEN_ID(GEN_SAUVEGARDE_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_SAUVEGARDE_ID, 0);
    if (tmp < new.ID_SAUVEGARDE) then
      tmp = GEN_ID(GEN_SAUVEGARDE_ID, new.ID_SAUVEGARDE-tmp);
  END
END^
SET TERM ; ^

CREATE INDEX IDX_FICHIER_DATE ON FICHIER (DATE_FICHIER);
CREATE INDEX IDX_FICHIER_EMPLACEMENT ON FICHIER (EMPLACEMENT_FICHIER);
CREATE INDEX IDX_FICHIER_ID_SAUVEGARDE ON FICHIER (ID_SAUVEGARDE);
CREATE UNIQUE DESCENDING INDEX IDX_SAUVEGARDE1 ON SAUVEGARDE (ID_SAUVEGARDE);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CHEMIN_SAUVEGARDE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FICHIER TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON HORAIRE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LISTE_EXCLUT TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LISTE_FICHIER TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PLANIF TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON SAUVEGARDE TO  SYSDBA WITH GRANT OPTION;



commit;
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('LUNDI', '0');
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('MARDI', '0');
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('MERCREDI', '0');
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('JEUDI', '0');
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('VENDREDI', '0');
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('SAMEDI', '0');
INSERT INTO PLANIF (JOUR, IS_SELECTED) VALUES ('DIMANCHE', '0');

INSERT INTO HORAIRE (HEURE, MINUTES, ARRET_MACHINE, ENVOI_MAIL_ST) VALUES ('0', '0', '0', '0');

commit;